### ISSUE TITLE
Null pointer...

### ISSUE THREAD

**Issue by BigTows** [BigTows/PinNote#1]
```
java.lang.NullPointerException
	at org.bigtows.note.visual.EvernoteVisualAdapter.hasTargetTreeItemInNotes(EvernoteVisualAdapter.java:271)
	at org.bigtows.note.visual.EvernoteVisualAdapter.syncTarget(EvernoteVisualAdapter.java:120)
	at org.bigtows.note.visual.EvernoteVisualAdapter.update(EvernoteVisualAdapter.java:111)
	at org.bigtows.note.visual.EvernoteVisualAdapter.lambda$uploadNotes$3(EvernoteVisualAdapter.java:529)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by BigTows** [comment]
on Create new Target...

**Comment by BigTows** [comment]
Необходимо, при создании нового  Target, проинициализировать его ID
