### ISSUE TITLE
Hide error alert when user in offline

### ISSUE THREAD

**Issue by BigTows** [BigTows/PinNote#11]
**Describe the bug**
Hide error alert when user in offline

**To Reproduce**
1. Turn off internet
2. Change notes
3. See error

**Exception**
```
org.bigtows.note.storage.exception.LoadNotesException: Error load notes
	at org.bigtows.note.storage.EvernoteStorage.tryGetAllRawNotes(EvernoteStorage.java:338)
	at org.bigtows.note.storage.EvernoteStorage.updateNotes(EvernoteStorage.java:164)
	at org.bigtows.note.visual.EvernoteVisualAdapter$1.run(EvernoteVisualAdapter.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.evernote.thrift.transport.TTransportException: java.net.UnknownHostException: www.evernote.com
	at com.evernote.thrift.transport.THttpClient.flush(THttpClient.java:154)
	at com.evernote.edam.notestore.NoteStore$Client.send_findNotes(NoteStore.java:1138)
	at com.evernote.edam.notestore.NoteStore$Client.findNotes(NoteStore.java:1124)
	at com.evernote.clients.NoteStoreClient.findNotes(NoteStoreClient.java:324)
	at org.bigtows.note.storage.EvernoteStorage.tryGetAllRawNotes(EvernoteStorage.java:326)
	... 15 more
Caused by: java.net.UnknownHostException: www.evernote.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.evernote.thrift.transport.THttpClient.flush(THttpClient.java:142)
	... 19 more

```

**Comment by BigTows** [comment]
New core..
