### ISSUE TITLE
Exception when remove notebook

### ISSUE THREAD

**Issue by BigTows** [BigTows/PinNote#8]
**Describe the bug**
Exception when remove notebook

**To Reproduce**
1. Run plugin
2. Go to Evernote
3. Remove Notebook `PinNote`

**Exception**
```
org.bigtows.note.storage.exception.LoadNotesException: Error load notes
	at org.bigtows.note.storage.EvernoteStorage.tryGetAllRawNotes(EvernoteStorage.java:312)
	at org.bigtows.note.storage.EvernoteStorage.updateNotes(EvernoteStorage.java:145)
	at org.bigtows.note.visual.EvernoteVisualAdapter$1.run(EvernoteVisualAdapter.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: EDAMNotFoundException(identifier:Notebook.guid, key:c5a1c3ee-agb8-4510-a14b-13b1a84732c4)
	at com.evernote.edam.notestore.NoteStore$findNotes_result.read(NoteStore.java:11818)
	at com.evernote.edam.notestore.NoteStore$Client.recv_findNotes(NoteStore.java:1153)
	at com.evernote.edam.notestore.NoteStore$Client.findNotes(NoteStore.java:1125)
	at com.evernote.clients.NoteStoreClient.findNotes(NoteStoreClient.java:324)
	at org.bigtows.note.storage.EvernoteStorage.tryGetAllRawNotes(EvernoteStorage.java:300)
	... 15 more
```

**Comment by BigTows** [comment]
New core..
